function log_data = get_logData_struct()

log_data = struct('Time_demo',[], 'yd_data',[], 'dyd_data',[], 'ddyd_data',[], ...
                  'D',[], 'Ts',[], 'g0', [], ...
                  'Time_train', [], 'F_train_data', [], 'Fd_train_data', [], ...
                  'Time',[],'y_data',[],'dy_data',[],'y_robot_data',[],'dy_robot_data',[],'z_data',[],'dz_data',[], ...
                  'x_data',[],'u_data',[], 'Fdist_data',[], 'Force_term_data',[], 'g_data', [], ...
                  'Psi_data', [], 'shape_attr_data',[], 'goal_attr_data', [], 'dmp', [], 'DMP_w', []);

end

