def test_force_mode_with_movej():

  pi = 3.14159
  deg2rad = pi/180

  joint_vel = 0.6
  joint_accel = 1.0
  Cart_vel = 1.2
  Cart_accel = 10.0

  init_joint_pos = [54*deg2rad, -62*deg2rad, 73*deg2rad, 14*deg2rad, 10*deg2rad, -1*deg2rad]
  goal_joint_pos = [-20*deg2rad, -80*deg2rad, 105*deg2rad, 30*deg2rad, 25*deg2rad, -15*deg2rad]

  task_frame = p[0, 0, 0, 0, 0, 0]
  selection_vector = [1, 1, 1, 1, 1, 1]
  wrench = [2, 2, 2, 1, 1, 1]
  type = 2
  limits = [0.5, 0.5, 0.5, 0.4, 0.4, 0.4]

  sleep(0.02)

  force_mode(task_frame, selection_vector, wrench, type, limits)

  while (True):
    #sync()
    movej(init_joint_pos, joint_vel, joint_accel)
    movej(goal_joint_pos, joint_vel, joint_accel)
  end

end
